In [ ]:
# Q.1 Convert a 1D array to a 2D array with 2 rows 

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6]) 

reshaped = arr.reshape(2, 3)       
print(reshaped)




[[1 2 3]
 [4 5 6]]


In [ ]:
# Q.2 Get the common items between a and b 

import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

common = np.intersect1d(a, b)

print(common)


[2 4]


In [ ]:
# Q.3 Get all items between 5 and 10 from a.

import numpy as np

a = np.array([2, 6, 1, 9, 10, 3, 27])

result = a[(a >= 5) & (a <= 10)]

print(result)


[ 6  9 10]
